language:
  - node_js

node_js:
  - '4.2'

branches:
  except:
    # Don't run on tag pushes
    - /^v\d+\.\d+\.\d+$/

notifications:
  slack: smartcar:PGJmjtKFPytU5E2FwsImdVp8

install:
  - git clone git@github.com:smartcar/build.git $HOME/smartcar-build
  - cp $HOME/smartcar-build/resources/Makefile .

  - npm install

script:
  - npm test
  - npm run cover
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - make create-tag

before_deploy:
  # This is to suppress some warnings thrown by Travis. This has no effect
  # otherwise
  - export PATH=/usr/local/rvm/gems/ruby-2.2.3/bin:$PATH

deploy:
  provider: script
  skip_cleanup: true
  script: make push-tag
  on:
    branch: master
