language:
  - node_js

node_js:
  - 8

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

notifications:
  slack: smartcar:PGJmjtKFPytU5E2FwsImdVp8

install:
  - git clone git@github.com:smartcar/build.git $HOME/smartcar-build
  - cp $HOME/smartcar-build/resources/Makefile .

  - npm install

script:
  - npm test
  - npm run cover
  - make create-tag
  - npm run build

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run publish
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: make push-tag
    on:
      branch: master
