sudo: required

language:
  - node_js

node_js:
  - '10'

services:
  - docker

if: tag IS blank # do not build tags

install:
  - npm ci

stages:
  - test
  - publish

jobs:
  include:
    - stage: test
      node_js: '10'
      before_install:
        - docker run --name selenium-container -d --net host -v /dev/shm:/dev/shm selenium/standalone-chrome
      script:
        - npm test
        - npm run cover
    - stage: publish
      node_js: '10'
      if: branch = master
      script: npx semantic-release
